name: Validate

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
          comment: false
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Integration validation
        uses: home-assistant/actions/hassfest@master
